export const contact = {
  authorName: "Trần Hạ Yểm",
  developerName: "Trần Ngọc Dương",
  email: "tranhayem@gmail.com",
  phone: "",
  address: "",
  github: "https://github.com/duongtranngoc",
  linkedin: "https://www.linkedin.com/in/tranhayem/",
  facebook: "https://www.facebook.com/tranhayem.info",
  instagram: "https://www.instagram.com/tranhayem/",
  twitter: "https://www.twitter.com/tranhayem",
  youtube: "https://www.youtube.com/@tranhayem",
  pinterest: "",
  medium: "",
  startYear: 2024,
  updateYear: 2024,
};
